[build] Provide some riscv64 compilation flags
-Wno-atomic-alignment is required to go past
../../zircon/kernel/include/kernel/brwlock.h:207:17: error: large atomic operation may incur significant performance penalty [-Werror,-Watomic-alignment]
      success = __atomic_compare_exchange_n(raw_state, &expected, desired, /*weak=*/false,
                ^

-mno-relax is required to go past
ld.lld: error: user.vdso-riscv64-clang.shlib/obj/system/ulib/zircon/syscall-asm.syscalls-riscv64.S.o:(.text+0x0): relocation R_RISCV_ALIGN requires unimplemented linker relaxation; recompile with -mno-relax

Change-Id: Ie917522e9bd9f7e10d7581525fc3596b770ae085